name: Cleanup Gitpod Environments

on:
  schedule:
    - cron: '0 3 * * *'   # Runs at 3:00 AM UTC (03:00) every day
  workflow_dispatch:      # Allows manual triggering

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Old Environments
        uses: Siddhant-K-code/cleanup-gitpod-environments@v1.1
        with:
          GITPOD_TOKEN: ${{ secrets.GITPOD_TOKEN }}
          ORGANIZATION_ID: ${{ secrets.GITPOD_ORGANIZATION_ID }}
          OLDER_THAN_DAYS: 7
          PRINT_SUMMARY: true